version: "3"
networks:
  expense:
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: 9689mahesh/mysql:v1
    container_name: mysql # --name mysql
    volumes:
      - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: 9689mahesh/backend:v1
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on: 
      - mysql
  frontend:
    image: 9689mahesh/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend